### PR TITLE
[Hotfix] Taking in to account nested templates for filters

### LINKED ISSUE #4009: Hotfix Grouped filters not rendering as checked.
The library template filters are not working as expected. When selecting a template that is in a group, the filter is applied but the filter is not rendered as selected.

Screenshot 2021-11-10 at 15 17 44

### PR DESCRIPTION
**Pull request by konzz**
fixes #4009

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/react/Library/components/TemplatesFilter.tsx [hunk 1]
```diff
@@ -33,13 +34,26 @@ const filterValidSelectedTemplates = (configuredFilters: string[], selectedTempl
     ? selectedTemplates.filter(t => configuredFilters.includes(t))
     : selectedTemplates;
 
+const flattenConfiguredFillters = (configuredFilters: SettingsFilterSchema[]) =>
```
Comment (mfacar) [inline app/react/Library/components/TemplatesFilter.tsx:37]: There's a typo in Filters

File: app/react/Library/components/TemplatesFilter.tsx [hunk 2]
```diff
@@ -33,13 +34,26 @@ const filterValidSelectedTemplates = (configuredFilters: string[], selectedTempl
...
+  configuredFilters.reduce((result: string[], filter) => {
+    if (filter.items && filter.items.length) {
+      const items = filter.items.map(item => item.id!);
+      // eslint-disable-next-line no-param-reassign
```
Comment (mfacar) [inline app/react/Library/components/TemplatesFilter.tsx:41]: this disable can be avoided if instead of concatenating just push the destructured elements with something like result.push(...items);

Comment (mfacar) [reply app/react/Library/components/TemplatesFilter.tsx:41]: can you add or update a test to cover this?

**Review by mfacar — CHANGES_REQUESTED** [review]
@konzz I checked the functionality and all is ok. Please review the comments I put in the code.

**Review by mfacar — APPROVED** [review]
LGTM!
