### PR TITLE
4895 - list of thesauri in alphabetical order in Select/Multiselect properties

### LINKED ISSUE #4895: Select/Multiselect properties: list of thesauri in alphabetical order
**Describe the bug**
When setting up a select or multiselect property in a template, the list of thesauri is not in alphabetical order.

**To Reproduce**
1. Go to Settings / Templates
2. Add or edit a Template
3. Choose a select or multiselect property
4. Click on "slect list"

**Expected behavior**
This list should be in alphavetical order.

**Screenshots**
image

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Brave, but could happen in anyone.

**Additional context**
The issue is particulary needed in instaces with too many thesauri.

### PR DESCRIPTION
**Pull request by mfacar**
fixes #4895 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/react/Templates/components/FormConfigSelect.js [hunk 1]
```diff
@@ -100,4 +107,5 @@ export function mapStateToProps(state, props) {
   };
 }
 
+export { FormConfigSelect };
```
Comment (Zasa-san) [inline app/react/Templates/components/FormConfigSelect.js]: I don't think this is ever used, can we remove this export?

Comment (mfacar) [reply app/react/Templates/components/FormConfigSelect.js]: Totally, thank you!
