### PR TITLE
4825 segmentations file delete fix

### LINKED ISSUE #4825: IX: review and add missing segmentation object flows
Deleting an entity and it's primary document does not delete the related segmentation (both in db, and xml on disk). 

-  make sure that entity deletion cleans up properly.
- go through the objects related to segmentations (entities, files), and review CRUD flows to make sure that the housekeeping is done in segmentations correctly in each case (create, update, delete)

### PR DESCRIPTION
**Pull request by LaszloKecskes**
fixes #4825 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/eventListeners.ts [hunk 1]
```diff
@@ -1,8 +1,10 @@
 import { EventsBus } from './eventsbus';
+import { registerEventListeners as registerSegmentationListeners } from './services/pdfsegmentation/eventListeners';
 import { Suggestions } from './suggestions/suggestions';
 
 const registerEventListeners = (eventsBus: EventsBus) => {
   Suggestions.registerEventListeners(eventsBus);
```
Comment (fnocetti) [inline app/api/eventListeners.ts:6]: As a note, I think we should take the register function out of the Suggestions object and leave it standalone just as the one for segmentation.

**Review by fnocetti — APPROVED** [review]
LGTM. Feel free to merge
