### PR TITLE
5423 csv export of selects with parents

### LINKED ISSUE #5423: Group name/label of group thesaurus not showing up within CSV export file
**Describe the bug**
Currently, on exporting entities with select type properties linked to group thesauri, the CSV file only carries the the nested value and not the name/label of the group it belongs to. This leaves out key group related information pertaining to that nested value, as well as creates confusion when a nested value appears across different groups in the same thesaurus. 

**To Reproduce**
1. Go to template with at least one property linked to group thesaurus and select all entities. 
2. Click on 'Export CSV' button
3. Scroll to column where property with group thesaurus in the exported CSV file is located
4. See that only nested value is shown without the corresponding group name/label

**Expected behavior**
The exported file carries the nested value with the group label. 

**Device (please select all that apply)**
 - [x] Desktop
 - [x] Mobile

**Browser**
Google

**Additional context**
NA

### PR DESCRIPTION
**Pull request by LaszloKecskes**
fixes #5423

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/csv/importEntity.ts [hunk 1]
```diff
@@ -96,16 +97,18 @@ const importEntity = async (
...
-      const attachmentFile = await importFile.extractFile(attachment);
-      await storage.storeFile(
-        attachmentFile.filename,
-        createReadStream(attachmentFile.path),
-        'attachment'
-      );
-      return files.save({ ...attachmentFile, entity: entity.sharedId, type: 'attachment' });
-    }, Promise.resolve());
+    await attachments
+      .split(csvConstants.multiValueSeparator)
```
Comment (LaszloKecskes) [inline app/api/csv/importEntity.ts:101]: Only line 101 changed, the rest is indentation.

**Review by daneryl — APPROVED** [review]
Looks good !
