### PR TITLE
6699 problems with v2 thesauri

### LINKED ISSUE #6676: Thesauri settings: order items
When adding a new item into a thesaurus, it goes to the last position.
If you need to set this new item more to the top of the list, it is not posible to drag and drop it easily.

### LINKED ISSUE #6696: Empty groups on thesaurus
**Describe the bug**
When creating a new thesaurus, you are allowed to create an empty group. 

**To Reproduce**
1. Go to thesauri settings screen
2. Add thesaurus
3. Add group
4. Simply put a name to the group and hit Add
5. If there is no other items, it seems you can save the group, but then you cant edit it to add items. If the thesaurus has items, then it throws an error when trying to save.

**Expected behavior**
Validate that groups cannot be created empty, and when deleting items in a group remove the whole group if it's left with no items.

### LINKED ISSUE #6699: Problems with V2 thesauri
After #6698 we detect the following critical problems:

Thesauri needs better testing in general.

```[tasklist]
### UI issues
- [x] When creating a group the sidepanel save button should say 'Add group'
- [x] When editing a group the sidepanel save button should say 'Edit group'
- [x] Same for item create and edit ('Add' / 'Edit')
- [x] On the settings -> thesauri and on each individual thesaurus, the EDIT button has a disabled look (the border is not "deep blue") and hovering over them has no action.
- [ ] https://github.com/huridocs/uwazi/issues/7043
- [ ] https://github.com/huridocs/uwazi/issues/6696
- [ ] https://github.com/huridocs/uwazi/issues/6959
- [ ] https://github.com/huridocs/uwazi/issues/6676
- [ ] https://github.com/huridocs/uwazi/issues/6906
- [x] It is not possible to translate thersaurus names or values
```

```[tasklist]
### Validation
- [x] Please see #6696
- [x] You can delete groups and items and there is no warning as to the effect that this will have on the collection. We could add a warning before saving letting users now what items where removed and that that will have an effect on entities using those items.
```

```[tasklist]
### Testing
- [x] Unit tests for helpers
- [x] Redo E2E, it must check effects of changing thesauri (or do some of this in a unit test)
- [x] Adding thesauri
- [x] Adding groups
- [x] Editing thesauri
- [x] Editing group names and group item names
- [x] Deleting items
- [x] All of the above checked with library
```

```[tasklist]
### Code quality
- [x] There are `ts-ignore`s. Those ts warning are right, and instead of ignoring we should fix them
- [x] eslint problems. Be careful about having an environment that displays eslint errors for import sorting, arrow function styles, self closing tags, etc.
```

### LINKED ISSUE #6959: Problems when importing a thesaurus from CSV file
**Describe the bug**
The system throws an error if you create a thesaurus and immediately try to import a CSV file.

**To Reproduce**
1. Go to '/settings/thesauri'.
2. Click on 'Add thesurus'
3. Type a thesaurus name
4. Click on 'Import', select a CSV file properly done. 
[Thesaurus Test.csv](https://github.com/user-attachments/files/16054872/Thesaurus.Test.csv)
5. Then you get the list of items:
image
6. Click on 'Save'.
7. you get an error:
image
8. However, if you come back to '/settings/thesauri' and edit the just created thesaurus again, the imported list is available.

**Expected behavior**
Errors should not appear, if the CSV file is properly imported.

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Brave

### LINKED ISSUE #7043: Thesauri / All items are deleted when trying to remove a duplicated value
**Describe the bug**
When adding an item in a thesaurus, if this value already exists and then you must delete it, the whole list of values disappear.

**To Reproduce**
1. Go to 'Settings - Thesauri' and select a thesaurus.
image

2. Add an item with a duplicate value on purpose.
image

3. When trying to save it, the system send a warning.
image

4. Select the duplicated item and click on Remove.
image

5. See error: every item has de dissappeared.
image

**Expected behavior**
Only the duplicated and selected item should be removed.

### PR DESCRIPTION
**Pull request by mfacar**
fixes #6699
fixes #6696
fixes #7043
fixes #6959
fixes #6676

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by Zasa-san** [comment]
First round of functional review. This is focused solely on the thesauri screen:

- Long labels look odd with the parenthesis on the 'translated'. Super minor thing, I think we can just leave it like that until we have a global solution for multiline values on tables. But maybe it's a quick fix.

image

- When you are adding a group you cannot create it empty. Is this intended? Considering that now empty groups have the placeholder row to add items to it.

- You can drag all the items out of a group and still save the thesauri. This makes the group into a root item. Is this intended? Should the validation fail or the group get deleted? (If you leave the `subRows` property as an empty array it should still register it as a group on the table).

- Editing a group with values is odd, because it lists all the thesauri inside it in the sidepanel. Maybe when you edit a group just show the group label? We are not offering ways of deleting the items inside, or sorting them, so makes no sense to have them there.

- Edit a group -> Change the name of one of the items inside it, or even the label of the group itself -> Save and close the sidepanel -> Open the sidepanel again. It’s empty.

- Expan a group -> edit a child -> save and close the sidepanel -> the change is applied to the group label, not the child label.

- Generally check the intended behavior of dnd. In prod you currently cannot drag items in or out of a group.

**Comment by Zasa-san** [comment]
Fiddling around with thessauri I see some inconsistencies in the `id` property of the database. Some of them have a long format `id`, other have what appears to be one of the client's ID generated codes. 

*Thesauri created/edited in this branch*
image

*Thesauri created/eited in development*
This is a thesauri created in development. The `id` property is consistent:

image

File: app/react/V2/Routes/Settings/Thesauri/ThesaurusForm.tsx [hunk 1]
```diff
@@ -1,212 +1,70 @@
...
+        <Translate>Thesauri added.</Translate>
+      ),
     });
-    setThesaurusValues(thesaurusValuesCopy);
-  };
-
-  const addGroupSubmit = (group: FormThesauriValue) => {
-    const thesaurusValuesCopy = thesaurusValues.filter(item => item._id !== group._id);
-    setThesaurusValues([...thesaurusValuesCopy, group]);
+    navigate(`../edit/${savedThesaurus._id}`);
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/ThesaurusForm.tsx]: Is this to reload the page? We have something similar here 
https://github.com/huridocs/uwazi/blob/cde642be4baffd54d9876c182d229ff08d58a900/app/react/V2/Routes/Settings/Pages/PageEditor.tsx#L86

The example also prevents a problems where if the user navigates back they would end up in the new thesaurus screen in some cases.

File: app/react/V2/Routes/Settings/Thesauri/components/TableComponents.tsx [hunk 2]
```diff
@@ -1,46 +1,39 @@
...
-        color="indigo"
-        className="bg-indigo-200 border-none rounded-md drop-shadow-none"
-      >
-        <Translate>Group</Translate>
-      </EmbededButton>
-    )}
-  </div>
-);
+const ThesaurusValueLabel = ({ getValue, cell }: CellContext<ThesaurusValueSchema, string>) => {
+  const { thesaurus } = cell.getContext().column.columnDef.meta!.data;
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/components/TableComponents.tsx:39]: Is this info nowhere on the `row`?

File: app/react/V2/Routes/Settings/Thesauri/components/TableComponents.tsx [hunk 3]
```diff
@@ -75,23 +68,30 @@ interface TableThesaurusValue extends ClientThesaurusValue, Omit<ClientThesaurus
...
-const columns = (actions: { edit: Function }) => [
+const columns = (actions: { edit?: Function }, thesaurus: ClientThesaurus) => [
   columnHelper.accessor('label', {
     id: 'label',
     header: LabelHeader,
     cell: ThesaurusValueLabel,
-    meta: { headerClassName: 'w-11/12' },
-  }) as ColumnDef<TableThesaurusValue, 'label'>,
+    meta: { headerClassName: 'w-11/12', data: { thesaurus } },
+  }) as ColumnDef<ThesaurusRow, 'label'>,
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/components/TableComponents.tsx]: The type should be inferred automatically. No need to cast it maybe?

File: app/react/V2/Routes/Settings/Thesauri/components/ThesauriTable.tsx [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+  currentThesauri: ThesauriRow[];
+  setSelectedThesauri: React.Dispatch<React.SetStateAction<ThesauriRow[]>>;
+}
+
+const ThesauriTable = ({ currentThesauri, setSelectedThesauri }: ThesauriTableProps) => {
+  const navigate = useNavigate();
+  const navigateToEditThesaurus = (thesaurus: Row<ThesauriRow>) => {
+    navigate(`./edit/${thesaurus.original._id}`);
+  };
+  const columnHelper = createColumnHelper<any>();
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/components/ThesauriTable.tsx]: You can use the type here, and avoid casting in every column definition below

File: app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx [hunk 5]
```diff
@@ -0,0 +1,469 @@
...
+          loader: editThesaurusLoader({}),
+        },
+      ],
+      {
+        initialEntries: ['/'],
+      }
+    );
+
+    const renderComponent = () => {
+      const reduxStore = createMockStore([thunk])(() => ({
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx]: If we incorporate this method of testing routes, the mock store default basic values should probably be extracted into the shared folder for V2 ``V2/shared`

File: app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,469 @@
...
+                      label: 'Child 1',
+                    },
+                    {
+                      label: 'new child 2',
+                    },
+                  ],
+                },
+              ],
+            },
+            undefined
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx]: Is this undefined in the expect correct?

File: app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx [hunk 7]
```diff
@@ -0,0 +1,469 @@
...
+          );
+        });
+      });
+    });
+
+    describe('Edit Thesaurus', () => {
+      it('should edit a root item', async () => {
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx:346]: There are some tests that don't have any `expect`s. Is that correct? How do you check if the test fails?

File: app/react/V2/Routes/Settings/Thesauri/specs/fixtures.ts [hunk 8]
```diff
@@ -0,0 +1,46 @@
+const thesauri = [
+  {
+    _id: 'thesaurus1',
+    name: 'Colors',
+    values: [{ _id: 't1_black', label: 'black', id: 'id1_black' }],
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/specs/fixtures.ts:5]: I don't think thesaurus values have `_id`. Just mentioning in case some test relies on it being there.

**Review by Zasa-san — CHANGES_REQUESTED** [review]
Lengthy review process, but it's looking great! 
I have some doubt's about test using `_id` in the fixtures for a thesaurus values. If there are cases where the client is inserting those `_id` in the values we should check to avoid putting them in rather than sanitizing them. (Unless I'm mistaken thesaurus values would not haven an `_id` property ever).

File: app/react/V2/Routes/Settings/Thesauri/components/TableComponents.tsx (hunk 3 above)
Comment (mfacar) [reply app/react/V2/Routes/Settings/Thesauri/components/TableComponents.tsx]: Totally!

File: app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx (hunk 6 above)
Comment (mfacar) [reply app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx]: It was expected because the headers are not passed to the calls of the API from the component, however, the methods are not called anywhere else so I removed the param in the API client.

File: app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx (hunk 7 above)
Comment (mfacar) [reply app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx:346]: It's a good one, I'm using screen.get... functions which fail in case the looken element doesn't exists in the document (a couple use screen.query... which doesn't fail if the element doesn't exist), also @testing-library/react/pure to keep the state between the tests, but adding expects definitively helps a lot with the readability of the tests, I added a function to check the right call of the save function where it applies.

File: app/react/V2/Routes/Settings/Thesauri/specs/fixtures.ts (hunk 8 above)
Comment (mfacar) [reply app/react/V2/Routes/Settings/Thesauri/specs/fixtures.ts:5]: I'm adding the _id to ensure the values are kept through the sanitization functions, this because #905 & #4053  suggest there could be values with _id, the component is only handling id given that that currently that is the property generated by the endpoint.

**Comment by mfacar** [comment]
Thank you @Zasa-san! 
> * Long labels look odd with the parenthesis on the 'translated'. Super minor thing, I think we can just leave it like that until we have a global solution for multiline values on tables. But maybe it's a quick fix.
- In the meantime, I added a border instead of the parenthesis.
> * When you are adding a group you cannot create it empty. Is this intended? Considering that now empty groups have the placeholder row to add items to it.
- In fact, an empty group could not be used as a valid option of a template property, a validation in the endpoint is also required, I created #7144 regarding to that.
> * You can drag all the items out of a group and still save the thesauri. This makes the group into a root item. Is this intended? Should the validation fail or the group get deleted? (If you leave the `subRows` property as an empty array it should still register it as a group on the table).
- I disabled the group edition due to #6906 and #7144.  By the moment if all the items of a group are deleted by selection, the group is also removed.
> * Editing a group with values is odd, because it lists all the thesauri inside it in the sidepanel. Maybe when you edit a group just show the group label? We are not offering ways of deleting the items inside, or sorting them, so makes no sense to have them there.
- I'm not sure about this, although it is different from other places where items can be deleted, you can also make a massive update of all the members without clicking each row. @juanmnl any thoughts? 
> * Edit a group -> Change the name of one of the items inside it, or even the label of the group itself -> Save and close the sidepanel -> Open the sidepanel again. It’s empty.
- Fixed
> * Expan a group -> edit a child -> save and close the sidepanel -> the change is applied to the group label, not the child label.
- OMG!, Thanks for this caught, it's fixed.

**Comment by mfacar** [comment]
> Fiddling around with thessauri I see some inconsistencies in the `id` property of the database. Some of them have a long format `id`, other have what appears to be one of the client's ID-generated codes.

For the record, @Zasa-san found the different formats for id are caused by adding values into a thesaurus from the metadata editor.   There is some legacy code in app/react/Thesauri/actions/thesauriActions.js that should be removed when we rewrite the related components.

Update: It was possible to have a long identification format by delegating the generation of IDs to the endpoint.

File: app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx (hunk 6 above)
Comment (Zasa-san) [reply app/react/V2/Routes/Settings/Thesauri/specs/Thesauri.spec.tsx]: Ok, if we are sure those headers are never passed, we can remove them.

File: app/react/V2/Routes/Settings/Thesauri/components/ThesauriTable.tsx [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+  currentThesauri: ThesauriRow[];
+  setSelectedThesauri: React.Dispatch<React.SetStateAction<ThesauriRow[]>>;
+}
+
+const ThesauriTable = ({ currentThesauri, setSelectedThesauri }: ThesauriTableProps) => {
+  const navigate = useNavigate();
+  const navigateToEditThesaurus = (thesaurus: Row<ThesauriRow>) => {
+    navigate(`./edit/${thesaurus.original._id}`);
+  };
+  const columnHelper = createColumnHelper<ThesauriRow>();
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/components/ThesauriTable.tsx]: I believe that the columnHelper and the columns themselves can be moved outside the component, they don't use anything from the component (only `edit` and that's passed when the columns are built in :59). I'm not sure how much it impacts component render time to rebuild all of this on every rerender, but it's safe to declare it outside. 

You could even momize the call to the column builder function and have it depend on the edit parameter. But maybe that's no so necessary.

File: app/react/V2/Routes/Settings/Thesauri/specs/helpers.spec.ts [hunk 10]
```diff
@@ -0,0 +1,464 @@
...
+  addSelection,
+  compareThesaurus,
+  removeItem,
+  sanitizeThesauri,
+  sanitizeThesaurusValues,
+  sortValues,
+  thesaurusAsRow,
+} from '../helpers';
+
+const thesaurusValues: {}[] = [
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/specs/helpers.spec.ts]: Just an idea, feel free to ignore it: use the correct type here and if you have type issues ts-ignore them with a message that explains why those incorrect values are there. Like _id is there to check correct sanitization, or why is the empty value array. Could be helpful for the next dev that has to come here.

Also useful for sanitizedThesaurusValues so that we are sure it's the correct expected values.

File: app/react/V2/Routes/Settings/Thesauri/EditThesaurus.tsx [hunk 11]
```diff
@@ -0,0 +1,220 @@
...
+          {selectedThesaurusValue.length === 0 && (
+            <div className="flex justify-between w-full">
+              <div className="flex gap-2">
+                <Button onClick={addItem}>
+                  <Translate>Add item</Translate>
+                </Button>
+                <Button styling="light" onClick={addGroup}>
+                  <Translate>Add group</Translate>
+                </Button>
+                <Button styling="light" onClick={sortValues(thesaurusValues, setThesaurusValues)}>
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Thesauri/EditThesaurus.tsx:162]: The table has it's own `sortingFn` prop that can be used to pass a custom sorting function. Could this not be used instead of a custom sorting function? Just rely on the table to run the sorting by title when this button is clicked? `app/react/V2/Routes/Settings/IX/IXSuggestions.tsx:252` does something like it.

File: cypress/e2e/settings/thesauri.cy.ts [hunk 12]
```diff
@@ -20,104 +25,212 @@ describe('Thesauri configuration', () => {
...
+    cy.contains('.item-document', 'País select').click();
+    cy.contains('.metadata-name-select', 'Colores Importados: Azul Importado');
+  });
+
+  it('should update the values in the entities', () => {
+    changeLanguage('English');
+    cy.get('.only-desktop a[aria-label="Settings"]').click();
     cy.contains('span', 'Thesauri').click();
-    cy.get('tbody tr:nth-of-type(1) input').should('be.disabled');
+    cy.contains('New Thesaurus')
```
Comment (Zasa-san) [inline cypress/e2e/settings/thesauri.cy.ts]: I think you can do a `cy.contains('tr', 'New Thesaurus').contains('button', 'Edit').click();` here

File: cypress/e2e/settings/thesauri.cy.ts [hunk 13]
```diff
@@ -1,11 +1,16 @@
 /* eslint-disable max-statements */
```
Comment (Zasa-san) [inline cypress/e2e/settings/thesauri.cy.ts:1]: The e2e snapshots fail locally for me. If they are green on the CI, I'm ok. It's a bit difficult for me to check that the e2e covers all the expected flows correctly, although.

**Review by Zasa-san — APPROVED** [review]
Amazing!

The remaining comments are suggestions, but generally I'm ok with merging as is.

File: cypress/e2e/settings/thesauri.cy.ts (hunk 12 above)
Comment (mfacar) [reply cypress/e2e/settings/thesauri.cy.ts]: Certainly, much simpler!

File: cypress/e2e/settings/thesauri.cy.ts (hunk 13 above)
Comment (mfacar) [reply cypress/e2e/settings/thesauri.cy.ts:1]: I have the same problem locally, the problem is reported in Cypress and happens when using Chrome as the browser, at the moment running with Electron or the console is the alternative to check the tests.

File: app/react/V2/Routes/Settings/Thesauri/EditThesaurus.tsx (hunk 11 above)
Comment (mfacar) [reply app/react/V2/Routes/Settings/Thesauri/EditThesaurus.tsx:162]: @Zasa-san I agree with you, but my attempt to use the sortingFn to update the sortingState from the table client turned into a more complex option, for sure I'm missing some part of the configuration, so for now I'll keeping the external sort function

**Comment by txau** [comment]
The problem with importing the CSV still persists. 

image

**Review by txau — APPROVED** [review]
LGTM
