### PR TITLE
Fixed new user password not being usable

### LINKED ISSUE #3209: Setting password upon user creation doesn't get saved
If you provide an specific password when creating user, the password won't be saved. You can the edit the user and save it afterwards and it will be saved.

### PR DESCRIPTION
**Pull request by grafitto**
fixes #3209 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by grafitto** [comment]
@daneryl @fnocetti I think this is ready for QA, the failing tests are related to the Markdown thing @konzz was talking about, and codeclimate errors could be ignored

File: app/api/activitylog/activitylogMiddleware.js [hunk 1]
```diff
@@ -38,13 +38,14 @@ export default (req, _res, next) => {
   if (mustBeLogged(baseurl, method, body)) {
     const time = Date.now();
     const expireAt = date.addYearsToCurrentDate(1);
-    if (body.password) body.password = '*****';
+    const bodyLog = { ...body };
```
Comment (grafitto) [inline app/api/activitylog/activitylogMiddleware.js:41]: @RafaPolit if body is undefined then `{ ...body }` resolves to an empty object `{}`, would it be okay to leave it that way instead of introducing a branch? @konzz

Comment (RafaPolit) [reply app/api/activitylog/activitylogMiddleware.js:41]: Yes, I think this is good enough.

Comment (grafitto) [reply app/api/activitylog/activitylogMiddleware.js:41]: This is ready for QA @RafaPolit

File: app/api/activitylog/activitylogMiddleware.js [hunk 2]
```diff
@@ -38,13 +38,14 @@ export default (req, _res, next) => {
...
+    if (bodyLog.password) bodyLog.password = '*****';
```
Comment (mfacar) [inline app/api/activitylog/activitylogMiddleware.js:42]: @grafitto there is a max-statements issue on codeclimate for this method, since all new lines are required, maybe we could reduce the old code by instance removing the constant for time and using it inline at the entry `time: Date.now()`, what do you think?

File: app/api/users/users.js [hunk 3]
```diff
@@ -178,7 +177,7 @@ export default {
     }
     const _user = await model.save({
       ...user,
-      password: await encryptPassword(random()),
+      password: await encryptPassword(user.password),
```
Comment (mfacar) [inline app/api/users/users.js:180]: Good catch @grafitto, please could you add a test to cover this, if I reverted the changes all tests are passing.

File: app/api/users/specs/users.spec.js [hunk 4]
```diff
@@ -148,6 +156,7 @@ describe('Users', () => {
           {
             username: 'without2fa',
             email: 'another@email.com',
+            password: 'mypass',
```
Comment (mfacar) [inline app/api/users/specs/users.spec.js:159]: Despite this addition is nice to check the whole object, it is not covering the main reason for the problem with the password, because it was originated at the middleware side. I think we should add a kind of integration test at the route in order to verify if users.save is called with the correct params, but since instrumentRoutes, the helper we are using for tests the api calls, is not executing the middlewares as part of the call, it's fine to omit the test for now.

File: app/api/activitylog/activitylogMiddleware.js (hunk 2 above)
Comment (grafitto) [reply app/api/activitylog/activitylogMiddleware.js:42]: Nice idea, will do that

**Comment by mfacar** [comment]
@grafitto LGTM, I left a couple of comments, please review them to be able to merge.

**Comment by grafitto** [comment]
> @grafitto LGTM, I left a couple of comments, please review them to be able to merge.

Will do that

File: app/api/activitylog/activitylogMiddleware.js (hunk 2 above)
Comment (grafitto) [reply app/api/activitylog/activitylogMiddleware.js:42]: I believe the tests are already testing the password as opposed to `random()`

File: app/api/users/users.js (hunk 3 above)
Comment (grafitto) [reply app/api/users/users.js:180]: I believe the tests are already testing the password as opposed to `random()`

Comment (mfacar) [reply app/api/users/users.js:180]: Actually no, I saw some tests that check the password, but since all of them are passing even without the new changes, there is no one that covers this case.

File: app/api/activitylog/activitylogMiddleware.js (hunk 2 above)
Comment (grafitto) [reply app/api/activitylog/activitylogMiddleware.js:41]: Done

**Comment by mfacar** [comment]
The team agree to close the PR until we could test this appropriately

**Comment by yuvadm** [comment]
I'd be happy to test this on `development` since #3367 is blocking me from deploying a new server - anything I need to know before?

**Comment by RafaPolit** [comment]
Please, merge this also as a hot fix to master with all the required flow.
