### PR TITLE
6715 - thesauri screen crash on dnd

### LINKED ISSUE #6715: Thesauri screen crash on dnd
**Describe the bug**
When dragging and dropping items in the thesauri screen you can cause the app to crash. This seems to involve dragging and dropping root items inside a group.

**To Reproduce**
1. Go to a thesaurus, for example "Region" thesaurus in demo
2. Create a group with at least one item (don't save yet)
3. Grab root items and start trying to drop them inside the group
4. See error eventually

**Expected behavior**
You should be able to drag items from root to group, group to group, and group to root.

**Screenshots**
image

**Device (please select all that apply)**
Desktop

**Browser**
Firefox

### PR DESCRIPTION
**Pull request by mfacar**
fixes #6715

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/react/V2/Components/UI/Table/TableBody.tsx [hunk 1]
```diff
@@ -48,6 +49,7 @@ const setRowId: <T>(
 // eslint-disable-next-line comma-spacing
 const TableBodyComponent = <T,>({
   draggableRows,
+  allowEditGroupsWithDnD,
   // eslint-disable-next-line react/jsx-no-useless-fragment
```
Comment (Zasa-san) [inline app/react/V2/Components/UI/Table/TableBody.tsx]: I think this can be removed

**Review by Zasa-san — CHANGES_REQUESTED** [review]
LGTM! This is a very good solution.

File: app/react/V2/Components/UI/Table/TableBody.tsx (hunk 1 above)
Comment (mfacar) [reply app/react/V2/Components/UI/Table/TableBody.tsx:53]: I checked it and the property is needed to initialize the DnDOperations settings that are needed [later](https://github.com/huridocs/uwazi/blob/6715-thesauri-screen-crash-on-dnd-rows/app/react/V2/Components/Layouts/DragAndDrop/useDnDContext.tsx#L27) in the draggable items. So I'm keeping it.
