### PR TITLE
4949 entity metadata inconsistency fix

### LINKED ISSUE #4949: "Ghost" metadata creating validation error on multi-edit
**Describe the bug**
When a template has been deleted and some relationships (or inherited relationships) exists on other templates pointing to the template that was deleted, multi-editing entities that had PREVIOUSLY FILLED data will fail validation.

Single-editing them works as expected as the process is sanitizing the data, but multi-editing flow means that "invalid" metadata properties are being sent to the backend.

**To Reproduce**
Steps to reproduce the behavior (theoretical, not fully tested, may require extra steps or looking into the scenario with more detail):
1. Have templates A and B
2. Assign to template A a relationship property to template B (may require inherited relationship, not sure)
3. Create entities on template A pointing to some entities on template B
4. Delete template B (this may require to remove the properties from template A?)
5. Try to bulk-edit entities in template A

**Screenshots**
image

### PR DESCRIPTION
**Pull request by LaszloKecskes**
fixes #4949 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+      this.handleEntity(await entities.next(), propertyData);
+      // eslint-disable-next-line no-await-in-loop
+      if (this.actions.length >= this.batchSize) await this.perform(db);
+    }
+    if (this.actions.length) await this.perform(db);
+  },
+
+  async up(db) {
+    this.actions = [];
+    this.reindex = false;
```
Comment (fnocetti) [inline app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js]: I'm not sure if a reindex is not needed. I agree it won't break anything not to do it. But how long will it take for entities to get reindexed as side effect of other operations? Maybe let's ask the team. Whatever we decide I'm ok with it!

File: app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+  reindex: false,
+
+  batchSize: 1000,
+
+  actions: [],
+
+  async getPropertyData(db) {
+    const templates = await db.collection('templates').find().toArray();
+    const indexed = Object.fromEntries(
+      templates.map(t => [t._id, t.properties ? new Set(t.properties.map(p => p.name)) : []])
```
Comment (fnocetti) [inline app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js]: I think the "else" case should be an empty set. I haven't properly got there but I saw some `.has` operations done, which array has not defined.

File: app/api/templates/specs/fixtures/fixtures.js [hunk 3]
```diff
@@ -43,47 +62,62 @@ export default {
...
+          type: propertyTypes.select,
+          content: templateToBeDeleted,
+          label: 'selectToBeDeleted',
+          name: 'selectToBeDeleted',
+        },
       ],
-      commonProperties: [{ name: 'title', label: 'Title' }],
+      commonProperties: [{ name: 'title', label: 'Title', type: 'text' }],
     },
     {
```
Comment (fnocetti) [inline app/api/templates/specs/fixtures/fixtures.js:106]: Is this case even possible? How can it happen that you have a select property and it's content is a template and not a thesauri?

**Review by fnocetti — APPROVED** [review]
I added a couple of comments. Up to you to decide what to do.
Mostly LGTM and works fine.

File: app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js (hunk 1 above)
Comment (LaszloKecskes) [reply app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js]: I was also torn on this one, and I've decided to go with the reindex just to be safe. Let's ask the team.

File: app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js (hunk 2 above)
Comment (LaszloKecskes) [reply app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js]: You're right. Corrected. I guess this is why typescript would be useful.

File: app/api/templates/specs/fixtures/fixtures.js (hunk 3 above)
Comment (LaszloKecskes) [reply app/api/templates/specs/fixtures/fixtures.js:106]: That is a good question. Since these were existing tests, I've just updated them assuming there were there for a reason. Let's also ask this from the team.

File: app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js (hunk 1 above)
Comment (LaszloKecskes) [reply app/api/migrations/migrations/92-remove_nonexisting_metadata/index.js]: As discussed in the standup, a reindex is necessary, left as it is.

File: app/api/templates/specs/fixtures/fixtures.js (hunk 3 above)
Comment (LaszloKecskes) [reply app/api/templates/specs/fixtures/fixtures.js:106]: Tests updated according to the discussion with @daneryl .
