### PR TITLE
Check that relationship type is not used in relationship property bef…

### LINKED ISSUE #5595: Deleting a relationship type doesn't check if type is being used in relationship property
**Describe the bug**
When a relationship type is being used in a relationship property and the user tries to delete it, the system will check for connections using the relationship type but not for uses in properties. I won't neither delete the property.
It results in an inconsistent state where relationship properties exist that doesn't have a valid relationship type.
Note that this isn't triggered if connections for the type exist because the other check will prevent it.

**To Reproduce**
1. Create a relationship type `relType1`
2. Have 2 templates: `A` and `B`
3. Create in `A` a relationship property that points to entities of template `B` and uses `relType1`
4. Delete `relType1`

**Current behavior**
The relationship type is deleted and the property persists on the template but with no, or invalid, relationship type.

**Expected behavior**
The model is left in a consistent state. Either you're not able to delete the relationship type or the property gets deleted as well.

### PR DESCRIPTION
**Pull request by fnocetti**
…ore deleting it

fixes #5595 #5596 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/templates/templates.ts [hunk 1]
```diff
@@ -304,5 +304,9 @@ export default {
     return model.count({ 'properties.content': thesauriId });
   },
 
+  async countByRelationType(relationTypeId: string) {
+    return model.count({ 'properties.relationType': relationTypeId });
```
Comment (LaszloKecskes) [inline app/api/templates/templates.ts]: It might be a bit much, but since we have collections with multiple templates that can have over a 100 properties, maybe adding an index for this on the model might be worth it, since it is not a big effort.

**Comment by LaszloKecskes** [comment]
We have discussed about the front end facing part of this issue. This is currently throwing an unhandled backend error. Will that be enough?

**Review by LaszloKecskes — CHANGES_REQUESTED** [review]
Code looks good, and functionally works, let's discuss the comments.

File: app/api/templates/templates.ts (hunk 1 above)
Comment (fnocetti) [reply app/api/templates/templates.ts]: 100 is not, IMO, a big number. Also, the deletes of relationship types shouldn't be frequent. I would say it doesn't justify the penalty of maintaining the index.

**Comment by fnocetti** [comment]
> We have discussed about the front end facing part of this issue. This is currently throwing an unhandled backend error. Will that be enough?

Let's talk about this. Pragmatically speaking, it is preventing an undesired situation the cheapest way possible. It is more or less what we agreed.

EDIT: let's check if we can make it more meaningful without touching the frontend.

**Comment by LaszloKecskes** [comment]
This was more of a double-checking question. If it was discussed, then it works.

**Review by LaszloKecskes — APPROVED** [review]
Questions discussed, looks good.

**Review by LaszloKecskes — APPROVED** [review]
Looks good.

**Review by LaszloKecskes — APPROVED** [review]
Everything as discussed.
