### PR TITLE
Tables migration

### LINKED ISSUE #7052: Migrate to new table
After #6826 is merged we need to use the new table for all the v2 UIs.

We should migrate all uses of `V2/Components/UI/Table` and replace it with `V2/Components/UI/TableV2`, and remove the corresponding story and test. Lastly, rename `TableV2` module, story, and test to `Table`.

This is important because `TableV2` handles groups differently and has a corrected dnd functionality. 

Keep in mind that the new table requires that all its rows and sub rows have a unique `rowId` to properly handle dnd, selection and grouping. 

Doing this migration will fix: #6431& #6432

Sections under Settings where migration to new table is needed:
- [ ] User & Groups
- [ ] Menu
- [ ] Pages
- [ ] Languages
- [ ] Translations
- [ ] Filters
- [ ] Bug in Filters: Moved here from issue #6820 
       **Describe the bug**
When a user extracts all the items from the group in the filter settings, the group becomes a filter. It seems to be a bug because we use entity types (templates) for the creation of primary filters; labels that we use for grouping should not become filters. As a result, when a former group name is displayed on the filters panel, it always shows 0 entities, because there is no template associated with it.
**To Reproduce**
     1. Go to Settings and navigate to Filters from the left menu
     2. Add group and add entity types to the group
     3. Save the change
     4. Drag all the entity types belonging to the group outside of the group
     5. See that the group is displayed as a filter item as a result
- [ ] Relationship Types
- [ ] Activity Log
- [ ] Uploads
- [ ] Migrate FileDropzone to use dnd-kit (from #7065)
       We should migrate FileDropzone to use dnd-kit, instead of react-dnd so that v2 uses one library for drag and drop functionality. There’s also a DragAndDrop.stories.tsx for an implementation of dnd that’s not used in v2 and should also be removed. If https://github.com/huridocs/uwazi/issues/7052 is done, react-dnd can be removed as a dependency.

### PR DESCRIPTION
**Pull request by Zasa-san**
fixes #7052 #6431

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/react/V2/Routes/Settings/Filters/components/helpers.ts [hunk 1]
```diff
@@ -60,65 +64,69 @@ const updateFilters = (
...
+  filters?.forEach(filter => {
+    const { rowId, subRows, ...sanitizedFilter } = { ...filter };
+
+    if (subRows && subRows.length === 0) {
+      return;
+    }
+
+    if (subRows) {
+      sanitizedFilter.items = subRows.map(item => {
+        const { rowId: itemRowId, _id, ...sanitizedItem } = { ...item };
```
Comment (mfacar) [inline app/react/V2/Routes/Settings/Filters/components/helpers.ts]: The destructuration of { ...item } seems not to be needed, actually { rowId: itemRowId, _id, ...sanitizedItem } could be directly in the params of the map like subRows.map(({rowId: itemRowId, _id, ...sanitizedItem }) => ...)

File: app/react/V2/Routes/Settings/Filters/FiltersTable.tsx [hunk 2]
```diff
@@ -70,43 +71,57 @@ const FiltersTable = () => {
...
         type: 'error',
         text: <Translate>An error occurred</Translate>,
         ...(response.message && { details: response.message }),
       });
     }
-
     setSettings(response);
     setDisabled(false);
     setHasChanges(false);
+    const formattedFilters = formatFilters(savedFilters || []);
```
Comment (mfacar) [inline app/react/V2/Routes/Settings/Filters/FiltersTable.tsx]: Could it be that the reported inconsistencies are related with keeping the local filters instead of the data in the response?

File: app/react/V2/Routes/Settings/Filters/components/FiltersSidepanel.tsx [hunk 3]
```diff
@@ -60,19 +60,21 @@ const FiltersSidepanel = ({
...
     });
 
-  const handleSave = (values: Omit<ClientSettingsFilterSchema, 'items'> & { items: string[] }) => {
-    const result = { ...values, items: formatSelected(values.items) };
+  const handleSave = (values: Omit<Filter, 'subRows'> & { subRows: string[] }) => {
+    const result = { ...values, subRows: formatSelected(values.subRows) };
 
     if (!filter?._id) delete result._id;
     if (!filter?.id) result.id = uniqueID();
+    if (result.rowId === defaultValues.rowId) result.rowId = uniqueID();
```
Comment (mfacar) [inline app/react/V2/Routes/Settings/Filters/components/FiltersSidepanel.tsx:77]: To avoid this comparison, uniqueID() could be assigned directly instead of the value 'NEW'

**Review by mfacar — CHANGES_REQUESTED** [review]
Great job! I did some tests having the following comments:
* The Filters page has some unexpected behaviors after doing some editions:
      - Editing an instance without filters, adding several filters, saving, deleting 1 filter, the table is emptied, the data is correct after reloading.
      - After some editions, DnD starts working wrongly, some elements can't be moved out or into a group, or moving an item into a group ends with moving other items into it or changing the order. Two times when this  happened, select all starts a loop rendering having the error "Maximum update depth exceeded"
* Some actions column headers don't have the bottom border. 
Screenshot 2024-08-28 191331
* Filters and Menu items are not translatable.
* It isn't clear to me what is the solution for #6431

There are also a couple of things from previous developments that maybe can be easily fixed in this PR.
- Filters action buttons have a different order than other pages
Screenshot 2024-08-28 192426
- Relationship Types show the translated value followed by the original name wrapped by parenthesis, this is different in other pages like templates 
Screenshot 2024-08-28 192927

**Comment by Zasa-san** [comment]
> Great job! I did some tests having the following comments:
> 
>     * The Filters page has some unexpected behaviors after doing some editions:
>       - Editing an instance without filters, adding several filters, saving, deleting 1 filter, the table is emptied, the data is correct after reloading.
>       - After some editions, DnD starts working wrongly, some elements can't be moved out or into a group, or moving an item into a group ends with moving other items into it or changing the order. Two times when this  happened, select all starts a loop rendering having the error "Maximum update depth exceeded"

This was a mistake in rowIds, fixed!

> 
>     * Some actions column headers don't have the bottom border.
This is a problem on all these new tables, if it's simple I'll fix it in this PR, otherwise it's going to be fixed separately.
> 
>     * Filters and Menu items are not translatable.

Menu items are translatable after saving. Can you confirm that? Translate them before saving would not be possible.
 
Filters it's a whole other problem. Groups are translatable after saving, they are part of the `Filters` context, but single filters are not. They are the actual template names and do not exist on the `Filters` context. I could make them translatable but the user would have no way of knowing that what they are translating is the NAME of the template, not the name of the filter. I will remove translate from the filter UI for items, since I don't think it's a good idea that users translate tamplate names by mistake.

>     * It isn't clear to me what is the solution for [Difficult to determine editing row on larger screens #6431](https://github.com/huridocs/uwazi/issues/6431)

Rows highlighted as you hover over them ;)
> 
> 
> There are also a couple of things from previous developments that maybe can be easily fixed in this PR.
> 
>     * Filters action buttons have a different order than other pages
Fixed!

>     * Relationship Types show the translated value followed by the original name wrapped by parenthesis, this is different in other pages like templates

That's right, removed the translate there.

File: app/react/V2/Routes/Settings/Filters/FiltersTable.tsx (hunk 2 above)
Comment (Zasa-san) [reply app/react/V2/Routes/Settings/Filters/FiltersTable.tsx]: Kinda yes. It was not a good idea to avoid using the revalidator.

File: app/react/V2/Routes/Settings/Filters/components/FiltersSidepanel.tsx (hunk 3 above)
Comment (Zasa-san) [reply app/react/V2/Routes/Settings/Filters/components/FiltersSidepanel.tsx:77]: Calling the function for uniqueID on the instantiation of the form was triggering a rerender loop. I had a hard time figuring out was was triggering the endless rerenders on the component and removing the uniqueID from the default values fixed it.

Comment (mfacar) [reply app/react/V2/Routes/Settings/Filters/components/FiltersSidepanel.tsx:77]: I got it, it doesn't matter 👍

**Review by mfacar — APPROVED** [review]
LGTM! Really important improvements! 💯

**Comment by aphilop** [comment]
Some questions/comments to check if they should be part of this PR:

- I am wondering why in the Filters table we don't show "Selected x of y" next to the Delete button when item(s) are selected?

image

- Same as above in the Uploads table. Also in this table the action buttons at the bottom are not at the left as in all other tables.

image

**Comment by Zasa-san** [comment]
> Some questions/comments to check if they should be part of this PR:
> 
> * I am wondering why in the Filters table we don't show "Selected x of y" next to the Delete button when item(s) are selected?
> 
> 
> 
> * Same as above in the Uploads table. Also in this table the action buttons at the bottom are not at the left as in all other tables.
> 

@aphilop We have a few UI inconsistencies in the settings screen that are the result of iterating over the designs as we develop each screen.

I would suggest having an issue to list these inconsistencies, and to work on it after we finish all the settings screens (I think only templates is missing now). 

We have this issue here to get started: https://github.com/huridocs/uwazi/issues/6424

And then some minor issues that could be solved on a final pass on the settings UI:

https://github.com/huridocs/uwazi/issues/2032
https://github.com/huridocs/uwazi/issues/6837
https://github.com/huridocs/uwazi/issues/6757
https://github.com/huridocs/uwazi/issues/6425
https://github.com/huridocs/uwazi/issues/6435

Usually we don't find time to address these minor issues, so it could be a good thing to compile them into a big one and solve them after we have migrated all the settings screens.
