### PR TITLE
Replaced Table component for html table with Inputs

### LINKED ISSUE #6675: Input fields in Translations are loosing focus when start typing in them
**Describe the bug**
Updating translation values under 'Settings > Translations' is very cumbersome. Whenever you click on a field in order to edit the value, the input field is loosing value after adding or deleting a character. You then have to click again in the field to able to proceed with the editing.

**To Reproduce**
1. Go to 'Settings > Translations'
2. Click on 'Translate' for an item in the corresponding table
3. Click on any input field with a translation value
4. Start typing
5. After entering or deleting a character the input field looses the focus

**Expected behavior**
When the input field has the focus you must be able to type/delete any number of characters without the input field loosing the focus

**Screenshots**
**Input field with focus**
image

**Input field loosing focus after one character is typed**
image

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Safari 17.5, Firefox 128.0 on macOS Sonoma 14.5

**Additional context**
Initial description when the issue was reporting:
When entering to any translations screen from /settings/translations/, every time you type a character, the screen blinks in a strange way.

### PR DESCRIPTION
**Pull request by konzz**
fixes #6675 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by Zasa-san** [comment]
The issue of the focus is fixed but there's a slight problem with filtering by untranslated terms:
[translationserror.webm](https://github.com/user-attachments/assets/b4a2c756-67a8-4e75-bbcd-b7c1b59a0818)

You can see that when filtering and unfiltering `Item 1` translation values are not shown correctly. Scrolling down to remove `Item 1` from view seems to fix this. But it could be a problem when saving if those values are incorrect.

File: app/react/V2/Routes/Settings/Translations/EditTranslations.tsx [hunk 1]
```diff
@@ -1,3 +1,5 @@
+/* eslint-disable react/jsx-props-no-spreading */
+/* eslint-disable react/no-multi-comp */
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Translations/EditTranslations.tsx]: This rule disable can be removed

File: app/react/V2/Routes/Settings/Translations/components/FormInput.tsx [hunk 2]
```diff
@@ -1,38 +0,0 @@
...
-
-  return (
-    <div>
-      <InputField
-        id={data.cell.getValue()}
-        label={data.cell.row.original.language}
-        hideLabel
-        disabled={submitting}
-        clearFieldAction={reset}
-        errorMessage={hasErrors ? <Translate>This field is required</Translate> : ''}
```
Comment (Zasa-san) [inline app/react/V2/Routes/Settings/Translations/components/FormInput.tsx:28]: By replacing this with the standard form input the `This field is required` message is not longer shown. Not a big deal but the error state for the new field is not that obvious, the border is not as red when it's not focused. In a long list an error might go unnoticed without this message.
