### PR TITLE
7697 errorCollector util for EntityData for MarkdownViewer

### LINKED ISSUE #7697: Pages cant handle missing properties when displayed for entities
**Describe the bug**
When trying to display a missing property, pages throw an error `trying to read value of undefined`, instead they should handle this scenario and in any case report it as info.

**To Reproduce**
- Create a page to display an entity template
- Display the value of an unexisting property: `<EntityData value-of="Fake Property" />`
- Visit the entity view

### PR DESCRIPTION
**Pull request by josh-huridocs**
fixes #7697

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/react/Markdown/MarkdownViewer.js [hunk 1]
```diff
@@ -38,6 +41,20 @@ class MarkdownViewer extends Component {
     return <Element {...props} key={index} />;
   }
 
+  componentDidMount() {
+    if (errorCollector.hasErrors()) {
+      errorCollector.report();
```
Comment (mfacar) [inline app/react/Markdown/MarkdownViewer.js:46]: I couldn't find a util function to log a message as Info that could be used in the client. How about reporting the error as console.info to avoid executing the noop or removing the function?

File: app/react/Markdown/components/specs/EntityData.spec.tsx [hunk 2]
```diff
@@ -11,7 +11,6 @@ import { EntityData, EntityDataProps } from '../EntityData';
 
 describe('EntityData Markdown', () => {
   let consoleErrorSpy: jasmine.Spy;
```
Comment (mfacar) [inline app/react/Markdown/components/specs/EntityData.spec.tsx]: This spy is no longer used.

File: app/react/Markdown/components/specs/EntityData.spec.tsx [hunk 3]
```diff
@@ -73,26 +72,4 @@ describe('EntityData Markdown', () => {
       expect(screen.getByText('Main Image translated')).toBeInTheDocument();
     });
   });
-
-  describe('Error handling (until upstream implementation is implemented)', () => {
```
Comment (mfacar) [inline app/react/Markdown/components/specs/EntityData.spec.tsx:77]: By deleting these specs we are losing the coverage for the error handling. Is it possible to test the dispatch of the warning instead?

**Review by mfacar — CHANGES_REQUESTED** [review]
LGTM! Just some minor things in the code to be checked :+1:

**Review by mfacar — APPROVED** [review]

**Review by mfacar — APPROVED** [review]
LGTM!
