### PR TITLE
5469 numeric fields validation

### LINKED ISSUE #5469: Numeric fields are not properly validated in post api/entities
**Describe the bug**
If you send a string value on a metadata property that is configured as numeric, the endpoint will not give a validation error and save the string in the DB.

**To Reproduce**
1. Configure a template with a numeric value
2. Use curl or other tool to save an entity with the numeric property filled with a string
3. A string is now saved on a property that should be a number

### PR DESCRIPTION
**Pull request by fnocetti**
fixes #5469 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/migrations/migrations/142-parse-numeric-fields/index.ts [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+      Object.keys(entity!.metadata || {}).forEach(propertyName => {
+        if (template.properties[propertyName].type === 'numeric') {
+          const candidateValue = entity!.metadata?.[propertyName]?.[0].value;
+          if (typeof candidateValue === 'string') {
+            updates[`metadata.${propertyName}`] = [{ value: parseFloat(candidateValue) }];
+          }
+        }
+      });
+
+      if (Object.keys(updates).length > 0) {
```
Comment (LaszloKecskes) [inline app/api/migrations/migrations/142-parse-numeric-fields/index.ts]: Consider using bulk write with some batch size. In my experience that can speed up entity based migrations a lot.

**Review by LaszloKecskes — CHANGES_REQUESTED** [review]
Aside from the one comment, it looks good and works!

File: app/api/migrations/migrations/142-parse-numeric-fields/index.ts (hunk 1 above)
Comment (fnocetti) [reply app/api/migrations/migrations/142-parse-numeric-fields/index.ts]: Nice catch, done!

**Review by LaszloKecskes — APPROVED** [review]

**Review by LaszloKecskes — APPROVED** [review]
