### PR TITLE
7866 - Transating via CSV updates UI

### LINKED ISSUE #7866: Translating interface terms in bulk with CSV import does not seem to work
**Describe the bug**
When trying to translate interface terms in bulk with CSV import, the system reports that translations are successfully imported, but the translated terms are not updated in the UI. After saving, the terms in question are indicated as untranslated. So it seems, the whole process of CSV import does not rely work.

**To Reproduce**
1. Go to `Settings`  > `Translations` > `Translate` User Interface
2. Import a valid CVS with translated Ui terms. For this example, I downloaded the current es.csv from the repository and translated a few terms in the beginning of the cvs.
3. The system reports back a message `Translations imported` but the terms in question are not updated into the UI (however they are visually indicated as translated)
4. Click on `Save`. Now the terms in questions are shown correctly as not translated.

**Expected behavior**
After uploading a CSV, any translated terms should be updated in the UI and indicated as translated after saving.

**Screenshots**

Part of the downloaded [es.csv](https://github.com/huridocs/uwazi/blob/development/contents/ui-translations/es.csv)

Image

---

CSV with first few terms translated 

Image

---

UI before uploading CSV

Image

---

UI after uploading CSV

Image

---

UI after saving

Image

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Safari 18.3.1 on macOS 15.3.2

### PR DESCRIPTION
**Pull request by Zasa-san**
fixes #7866

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/react/V2/Routes/Settings/Translations/EditTranslations.tsx [hunk 1]
```diff
@@ -225,25 +219,25 @@ const EditTranslations = () => {
...
+          text: <Translate>Translations saved</Translate>,
         });
         break;
 
-      case fetcher.data instanceof FetchResponseError:
+      case fetcher.formData?.get('intent') === 'file-upload':
         setNotifications({
-          type: 'error',
-          text: <Translate>An error occurred</Translate>,
-          details: fetcher.data.json?.prettyMessage ? fetcher.data.json?.prettyMessage : undefined,
```
Comment (mfacar) [inline app/react/V2/Routes/Settings/Translations/EditTranslations.tsx:246]: I was thinking that we lost the error handling here, but I checked against production, and it actually doesn't do anything about errors.

**Review by mfacar — APPROVED** [review]
LGTM! Nice fix and covering for inline translation

File: app/react/V2/Routes/Settings/Translations/EditTranslations.tsx (hunk 1 above)
Comment (Zasa-san) [reply app/react/V2/Routes/Settings/Translations/EditTranslations.tsx:246]: I don't follow, currently if the backend returns an error it should be notified. Is that not working?

Comment (mfacar) [reply app/react/V2/Routes/Settings/Translations/EditTranslations.tsx:246]: There isn't an error notification. It isn't due to this change; it isn't in production either.
