### PR TITLE
HOTFIX Adjust password recovery ttl. Validate empty login credentials.

### LINKED ISSUE #6834: The "create password" process for new user fails
**Describe the bug**
When a new user tries to create a password, the process fails. As a consequence, the user cannot login to their account.

**To Reproduce**
1. Create a new user
2. Open the link to create a password in the welcome email
3. Use the form to provide a password and click save

**Expected behavior**
The user must be able to create a password that can use to log in their account.

**Screenshots**

Error message

image

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Safari 17.5 on MacOS 12.7.5

### LINKED ISSUE #6860: Login + blank password + hitting enter bricks the instance for that particular user
Attempting to login into Uwazi with a blank password AND hitting the enter key (not hitting the login button with the mouse) will brick the instance for that particular user due to something related with the cookie. It will display this error:

image

And attempting to reload the instance will show how it is bricked.

image

Clearing the cookies for this instance will resolve the problem.

### PR DESCRIPTION
**Pull request by fnocetti**
fixes #6860 
fixes #6834 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

File: app/api/auth/routes.js [hunk 1]
```diff
@@ -46,8 +46,8 @@ export default app => {
         body: {
           type: 'object',
           properties: {
-            username: { type: 'string' },
-            password: { type: 'string' },
+            username: { type: 'string', minLength: 1 },
+            password: { type: 'string', minLength: 1 },
```
Comment (aphilop) [inline app/api/auth/routes.js:50]: If I understand correctly, this would allow a password of one character, right?
Shouldn't a password be at least 8 characters in length (the current best practice)?

Comment (konzz) [reply app/api/auth/routes.js:50]: Yes, but we don't have that policy right now, so if we put that validation in the login we will block many users from being able to log in, probably we will need to change the creation/edition of passwords, and then after some time maybe change it here.

Comment (fnocetti) [reply app/api/auth/routes.js:50]: Yeah, I think we are mixing stuff :) We might definitively want to revisit our password policy. That's on user creation and password updates, where we decide what password a user can have.
This is the login. Technically, a user can try to login with any password, as long as they provide some.

Comment (aphilop) [reply app/api/auth/routes.js:50]: Ok, thanks for clarifying.

**Review by LaszloKecskes — APPROVED** [review]
Functionally tested both issues, works as intended.

Approved with the understanding that issues will be written for the outstanding tech debt (testing, other non-critical fixes).

**Comment by fnocetti** [comment]
Thanks @LaszloKecskes. For the record, this is the tech debt issue #6862
